### ISSUE TITLE
Does one profile allow multiple fanout?

### ISSUE THREAD

**Issue by snakwu** [networkservicemesh/fanout#12]
Does one profile allow multiple fanout?
Used for dns shunt parallel query

**Comment by edwarnicke** [comment]
@snakwu Could you say more about what you are asking?  If I'm reading your question correctly the answer is yes...but I'm not sure I'm reading it correctly :)

@denis-tingajkin

**Comment by snakwu** [comment]
> @snakwu Could you say more about what you are asking?  If I'm reading your question correctly the answer is yes...but I'm not sure I'm reading it correctly :)
> 
> @denis-tingajkin 

我一直关注你的这个插件，我想用来做dns分流，不知道一个区域，可用多次这个插件吗？

**Comment by snakwu** [comment]
> > @snakwu Could you say more about what you are asking?  If I'm reading your question correctly the answer is yes...but I'm not sure I'm reading it correctly :)
> > 
> > @denis-tingajkin 
> 
> 我一直关注你的这个插件，我想用来做dns分流，不知道一个区域，可用多次这个插件吗？

还有，except参数，可否改用map查询列表方式来排除，except列表我填了7万多个域名

**Comment by edwarnicke** [comment]
@snakwu apologies... I cannot read chinese

**Comment by snakwu** [comment]
> @snakwu apologies... I cannot read chinese

online translation?

**Comment by denis-tingajkin** [comment]
Hello @snakwu,

> Does one profile allow multiple fanout?

If you meant something like this
```
. {
    fanout . {IP1} {IP2} {
        except domain-a domain-b domain-c 
    }
    fanout domain-a {IP3} {IP4} {
        except domain-b domain-c
    }
    fanout . {IP5} {IP6}
}
```
then yes, it does.

> except列表我填了7万多个域名

Interesting case... I'm not sure that it will work fast because of  `expect` directive handling linear(it was not designed for a ton of labels).

Did you ask  Coredns about the case with 70 000 ignore domains? Probably they have some plugin for ignoring a ton of domains.

**Comment by snakwu** [comment]
> Hello @snakwu,
> 
> > Does one profile allow multiple fanout?
> 
> If you meant something like this
> 
> ```
> . {
>     fanout . {IP1} {IP2} {
>         except domain-a domain-b domain-c 
>     }
>     fanout domain-a {IP3} {IP4} {
>         except domain-b domain-c
>     }
>     fanout . {IP5} {IP6}
> }
> ```
> 
> then yes, it does.
> 
> > except列表我填了7万多个域名
> 
> Interesting case... I'm not sure that it will work fast because of `expect` directive handling linear(it was not designed for a ton of labels).
> 
> Did you ask Coredns about the case with 70 000 ignore domains? Probably they have some plugin for ignoring a ton of domains.

coredns需说不能超16个，但我填了7万个也一样工作，但怎才让他更好的工作是个问题

**Comment by snakwu** [comment]
> Hello @snakwu,
> 
> > Does one profile allow multiple fanout?
> 
> If you meant something like this
> 
> ```
> . {
>     fanout . {IP1} {IP2} {
>         except domain-a domain-b domain-c 
>     }
>     fanout domain-a {IP3} {IP4} {
>         except domain-b domain-c
>     }
>     fanout . {IP5} {IP6}
> }
> ```
> 
> then yes, it does.
> 
> > except列表我填了7万多个域名
> 
> Interesting case... I'm not sure that it will work fast because of `expect` directive handling linear(it was not designed for a ton of labels).
> 
> Did you ask Coredns about the case with 70 000 ignore domains? Probably they have some plugin for ignoring a ton of domains.

. {
    fanout . {IP1} {IP2} {
        except domain-a domain-b domain-c 
    }
    fanout . {IP3} {IP4}
}
cache

这样配置可以吗，我想要的是不在except列表的用IP1和IP2查询，如果在列表的就跳转到下个fanout用IP3和IP4查询

**Comment by denis-tingajkin** [comment]
> coredns需说不能超16个，但我填了7万个也一样工作，但怎才让他更好的工作是个问题

Probably we can improve `except` directive to allow it to load entries from file... Also need to think about how to store these entries in memory to have fast answers about is domain ignored. If you have some ideas you can prepare a patch.

There are two entry points if you want to patch it:
1. https://github.com/networkservicemesh/fanout/blob/master/setup.go#L162 //add somehow loading from the file here
2. https://github.com/networkservicemesh/fanout/blob/master/fanout.go#L141 //somehow smart handle a ton of ignoring domains(for example it should work fast for 70 000 entries)

> 这样配置可以吗，我想要的是不在except列表的用IP1和IP2查询，如果在列表的就跳转到下个fanout用IP3和IP4查询

Yes, in general, it should work. Let us know if it will not work :)

**Comment by snakwu** [comment]
> > coredns需说不能超16个，但我填了7万个也一样工作，但怎才让他更好的工作是个问题
> 
> Probably we can improve `except` directive to allow it to load entries from file... Also need to think about how to store these entries in memory to have fast answers about is domain ignored. If you have some ideas you can prepare a patch.
> 
> There are two entry points if you want to patch it:
> 
> 1. https://github.com/networkservicemesh/fanout/blob/master/setup.go#L162 //add somehow loading from the file here
> 2. https://github.com/networkservicemesh/fanout/blob/master/fanout.go#L141 //somehow smart handle a ton of ignoring domains(for example it should work fast for 70 000 entries)
> 
> > 这样配置可以吗，我想要的是不在except列表的用IP1和IP2查询，如果在列表的就跳转到下个fanout用IP3和IP4查询
> 
> Yes, in general, it should work. Let us know if it will not work :)

Thank you very much！如果说用map的算法是否能更有效的工作？其体我也不懂

**Comment by snakwu** [comment]
> > coredns需说不能超16个，但我填了7万个也一样工作，但怎才让他更好的工作是个问题
> 
> Probably we can improve `except` directive to allow it to load entries from file... Also need to think about how to store these entries in memory to have fast answers about is domain ignored. If you have some ideas you can prepare a patch.
> 
> There are two entry points if you want to patch it:
> 1. https://github.com/networkservicemesh/fanout/blob/master/setup.go#L162 //add somehow loading from the file here
> 2. https://github.com/networkservicemesh/fanout/blob/master/fanout.go#L141 //somehow smart handle a ton of ignoring domains(for example it should work fast for 70 000 entries)
> 
> > 这样配置可以吗，我想要的是不在except列表的用IP1和IP2查询，如果在列表的就跳转到下个fanout用IP3和IP4查询
> 
> Yes, in general, it should work. Let us know if it will not work :) 

. {
    fanout . {IP1} {IP2} {
        except domain-a domain-b domain-c 
    }
    fanout . {IP3} {IP4}
}

is not work!
plugin/fanout: this plugin can only be used once per Server Block

**Comment by denis-tingajkin** [comment]
> 如果说用map的算法是否能更有效的工作？

Not sure that we can just use a map there. I think first we need to check how works this methodhttps://github.com/coredns/coredns/blob/master/plugin/normalize.go#L21.

> is not work!
plugin/fanout: this plugin can only be used once per Server Block

Oops, I forgot that we have this check.
_comment above is updated _

**Comment by snakwu** [comment]
> > 如果说用map的算法是否能更有效的工作？
> 
> Not sure that we can just use a map there. I think first we need to check how works this method https://github.com/coredns/coredns/blob/master/plugin/normalize.go#L21.
> 
> > is not work!
> plugin/fanout: this plugin can only be used once per Server Block
> 
> Oops, I forgot that we have this check.
> 
> _Comment above is updated_ 

据我了解到，有人修改了forward实现map算法，请参考：
https://github.com/missdeer/coredns_custom_build/blob/master/forward-setup.go.patch

https://github.com/missdeer/coredns_custom_build/blob/master/forward.go.patch

**Comment by denis-tingajkin** [comment]
Interesting, then you can just apply this patch for fanout plugin. Also, you need to add an option to load ton entries from the file. I suggest adding here https://github.com/networkservicemesh/fanout/blob/master/setup.go#L155 case `except-file`.

**Comment by snakwu** [comment]
> Interesting, then you can just apply this patch for fanout plugin. Also, you need to add an option to load ton entries from the file. I suggest adding here https://github.com/networkservicemesh/fanout/blob/master/setup.go#L155 case `except-file`.

soory!我对修改代码不是很熟悉，还得靠你们实现！非常感谢这么好的项目

**Comment by denis-tingajkin** [comment]
@edwarnicke Do you have any concerns related to this fanout improvement?

**Comment by edwarnicke** [comment]
@denis-tingajkin I don't think so... it sounds like you are simply adding additional functionality, not changing core functionality... delighted that this is useful to others :)

**Comment by snakwu** [comment]
何时能实现map算法？

**Comment by denis-tingajkin** [comment]
@snakwu I'll discuss it today with the team.
Also, I've discussed with Coredns guys, they plan to add a specific plugin for your case. Can you check is this [plugin](https://github.com/miekg/block) suitable for you?

**Comment by snakwu** [comment]
> @snakwu I'll discuss it today with the team.
> Also, I've discussed with Coredns guys, they plan to add a specific plugin for your case. Can you check is this [plugin](https://github.com/miekg/block) suitable for you?

这个插件不合适我，我要实现的是在这个列表中的域名就跳转到下一个插件

**Comment by denis-tingajkin** [comment]
@fkautz can we spend time on this issue? It will not be used in NSM scenarios but can be used by fanout plugin users.

**Comment by denis-tingajkin** [comment]
@snakwu PR has been merged, can you please check is this problem still actual?

**Comment by snakwu** [comment]
> @snakwu PR has been merged, can you please check is this problem still actual?

ok，马上测试，等了两天了，为什么每次合并都要等待那么久！

**Comment by snakwu** [comment]
> @snakwu PR has been merged, can you please check is this problem still actual?

我填写了7万多8万条except，现在明显比之前快了！！

**Comment by denis-tingajkin** [comment]
>我填写了7万多8万条except，现在明显比之前快了！！

@snakwu Sounds good. Can we close this issue?

**Comment by snakwu** [comment]
> > 我填写了7万多8万条except，现在明显比之前快了！！
> 
> @snakwu Sounds good. Can we close this issue?

ok，这个map算法还是有效的，这个issue可以关了，有问题我再及时反馈，非常感谢你的付出！

**Comment by denis-tingajkin** [comment]
Fixed by https://github.com/networkservicemesh/fanout/pull/17

**Comment by snakwu** [comment]
> >我填写了7万多8万条except，现在明显比之前快了！！
> 
> @snakwu Sounds good. Can we close this issue?

但还有一个发现，就是在多个dns服务器中查询问题，往往反回的不是最快的ip查询结果，还麻烦你留意下这方面看可不可以优化一下，谢谢

**Comment by snakwu** [comment]
@denis-tingajkin 
关于except-file的用法，这个文件格式应该是怎么样写这个，用except写在配置里面，不是以except-file单独一个文件，那个效率更高？
