### ISSUE TITLE
关于except-file用法问题？

### ISSUE THREAD

**Issue by snakwu** [networkservicemesh/fanout#18]
关于except-file的用法，这个文件格式应该是怎么样写这个，用except写在配置里面，不是以except-file单独一个文件，那个效率更高？
 ps：如果except-file文件更新了，他对于reload有效吗？会重新加载吗？又或者可不可以做个检测，当except-file的文件改变时，重新reload coerdns？

**Comment by denis-tingajkin** [comment]
@snakwu could you please create issues on English? It can help other people understand what happening :)

**Comment by snakwu** [comment]
> @snakwu could you please create issues on English? It can help other people understand what happening :) 

With regard to the use of except-file, how should this file format be written in this, written in the configuration with except, instead of except-file as a single file, which is more efficient? Ps: if the except-file file is updated, is it valid for reload? Will it be reloaded? Or can we do a test to re-reload coerdns? when the except-file file changes?

**Comment by snakwu** [comment]
> @snakwu could you please create issues on English? It can help other people understand what happening :)

可不可以当except-file改变时,coerdns程序自动reload?

**Comment by denis-tingajkin** [comment]
> Can the coerdns program automatically reload when the except-file changes?

@snakwu No, it can't. To apply changes in this case you need to somehow reload your coredns.

**Comment by snakwu** [comment]
> > Can the coerdns program automatically reload when the except-file changes?
> 
> @snakwu No, it can't. To apply changes in this case you need to somehow reload your coredns.

需要怎么做才可以reload coredns？

**Comment by snakwu** [comment]
> > Can the coerdns program automatically reload when the except-file changes?
> 
> @snakwu No, it can't. To apply changes in this case you need to somehow reload your coredns.

我想要实现的时，用一个脚本定时更新except-file，然后except-file更新后，reload coerdns

**Comment by denis-tingajkin** [comment]
> 需要怎么做才可以reload coredns？

You can ask coredns guys about reloading.

**Comment by snakwu** [comment]
> `except` + reload plugin
except + reload plugin???

**Comment by snakwu** [comment]
> fanout ... {
>     except ....
> }
> reload 5s

我就是这样配置的,但是这个 reload 只检查coredns,Corefile有没有变动!

**Comment by denis-tingajkin** [comment]
`except-file` is not supported by `reload` plugin. `except-file` should be used only for static initialization of excluding domains.
For your case I see two ways:
1. Use `except-file` and somehow reload coredns instance. (I think you need ask coredns guys about reloading coredns instance)
2. Use `except` directive and `reload` plugin.

**Comment by snakwu** [comment]
> `except-file` is not supported by `reload` plugin. `except-file` should be used only for static initialization of excluding domains.
> For your case I see two ways:
> 1. Use `except-file` and somehow reload coredns instance. (I think you need ask coredns guys about reloading coredns instance)
> 2. Use `except` directive and `reload` plugin.

ok，我明白了，兄弟，谢谢！
