### ISSUE TITLE
make error！！

### ISSUE THREAD

**Issue by snakwu** [networkservicemesh/fanout#24]
Cloning into 'coredns'...
remote: Enumerating objects: 84, done.                                                 remote: Counting objects: 100% (84/84), done.                                          remote: Compressing objects: 100% (78/78), done.                                       remote: Total 56977 (delta 18), reused 17 (delta 6), pack-reused 56893                 Receiving objects: 100% (56977/56977), 95.41 MiB | 15.18 MiB/s, done.
Resolving deltas: 100% (30620/30620), done.
go generate coredns.go
CGO_ENABLED=0  go build -v -ldflags="-s -w -X github.com/coredns/coredns/coremain.GitCommit=49337b7d-dirty" -o coredns
go: finding github.com/networkservicemesh/fanout latest
github.com/networkservicemesh/fanout
# github.com/networkservicemesh/fanout
../../pkg/mod/github.com/networkservicemesh/fanout@v0.0.0-20200501063404-a86deaf0ed50/setup.go:60:3: undefined: metrics.MustRegister
make: *** [Makefile:16: coredns] Error 2

**Comment by snakwu** [comment]
@ denis-tingajkin

**Comment by denis-tingajkin** [comment]
@snakwu is the issue fixed?
