### ISSUE TITLE
Update coredns dependency to v1.7.1

### ISSUE THREAD

**Issue by snakwu** [networkservicemesh/fanout#26]
@denis-tingajkin  coerdns v1.7.1 is out！
It is hoped that compilation errors can be fixed.

**Comment by denis-tingajkin** [comment]
Hello @snakwu ,

I cannot find release `v.1.7.1` in coredns repository https://github.com/coredns/coredns/tags
Also there are no new releases https://github.com/coredns/coredns/releases

**Comment by snakwu** [comment]
> Hello @snakwu ,
> 
> I cannot find release `v1.7.1` in coredns repository https://github.com/coredns/coredns/tags
> Also there are no new releases https://github.com/coredns/coredns/releases

https://github.com/coredns/coredns/commit/ecd61a21656a7d6f6d87e3b74ad4e70a24c420c9

**Comment by snakwu** [comment]
好像只更新了1.7.1的 notes！

**Comment by denis-tingajkin** [comment]
@snakwu ok, then let's just wait for release :)

**Comment by snakwu** [comment]
> @snakwu ok, then let's just wait for release :)



> @snakwu ok, then let's just wait for release :)

Why is it so complicated now? It has always been possible to compile with the master before!
ps: I hope fanout can support DOH, thank you!

**Comment by snakwu** [comment]
@denis-tingajkin  
https://github.com/coredns/coredns/commit/aa82ca62fb048562ffaf4aa24d3f2db8d8bd0333

**Comment by denis-tingajkin** [comment]
@snakwu nice!
I think they soon will update:
https://github.com/coredns/coredns/tags
https://github.com/coredns/coredns/releases

**Comment by snakwu** [comment]
> @snakwu nice!
> I think they soon will update:
> https://github.com/coredns/coredns/tags
> https://github.com/coredns/coredns/releases

is out！！！

**Comment by snakwu** [comment]
@denis-tingajkin  
v1.7.1 is out

**Comment by denis-tingajkin** [comment]
@snakwu PR is merged. Is the problem solved?

**Comment by snakwu** [comment]
> @snakwu PR is merged. Is the problem solved?

ok，Resolved！thx！！！
ps：Can you support DOH??

**Comment by denis-tingajkin** [comment]
> Can you support DOH??

Could you open separate issue for this question?
