### ISSUE TITLE
Cannot build with CoreDNS 1.8.0

### ISSUE THREAD

**Issue by alitvak69** [networkservicemesh/fanout#30]
github.com/networkservicemesh/fanout
# github.com/networkservicemesh/fanout
/go/pkg/mod/github.com/networkservicemesh/fanout@v0.0.0-20200922050102-147700525660/setup.go:53:21: cannot use c (type *"github.com/caddyserver/caddy".Controller) as type *"github.com/coredns/caddy".Controller in argument to dnsserver.GetConfig
/go/pkg/mod/github.com/networkservicemesh/fanout@v0.0.0-20200922050102-147700525660/utils.go:39:12: undefined: "github.com/coredns/coredns/plugin/dnstap".TapperFromContext
/go/pkg/mod/github.com/networkservicemesh/fanout@v0.0.0-20200922050102-147700525660/utils.go:44:7: undefined: "github.com/coredns/coredns/plugin/dnstap/msg".New

**Comment by denis-tingajkin** [comment]
Fixed with #31
